#!/usr/bin/env python
"""VTK files reader class
This class aims to simplyfie the reading in of vtk files generated by the BEST
tools."""

__author__     = "Nils Wenzler"
__copyright__  = "Nils Wenzler"
__version__    = '1'
__maintainer__ = "Nils Wenzler"
__email__      = "wenzlern@ethz.ch"

#imports
import sys
from vtk import *
import glob
import os
from vtk.util.numpy_support import vtk_to_numpy
import numpy as np


# Read the source files
reader = vtkUnstructuredGridReader()
output = []
scalar_range = []
concentration = []

folder = sys.argv[1]
index = int(sys.argv[2])

for filename in glob.iglob(os.path.join(folder, '*.vtk')):
  reader.SetFileName(filename)
  reader.Update()
  pointdata = reader.GetOutput().GetCellData().GetScalars()
  concentration.append(vtk_to_numpy(pointdata))


for timestep in concentration:
  for i in range(len(timestep[:][0][0])):
    mean(timestep[i][:][:])
