#!/usr/bin/env python
"""VTK files reader class
This class aims to simplyfie the reading in of vtk files generated by the BEST
tools."""

__author__     = "Nils Wenzler"
__copyright__  = "Nils Wenzler"
__version__    = '1'
__maintainer__ = "Nils Wenzler"
__email__      = "wenzlern@ethz.ch"

#imports
import sys
import vtk


